#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_S2RINGS_DHZ2_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_S2RINGS_DHZ2_
const uint8_t S2Rings_DHZ2[] = {
	255,255,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_S2RINGS_DHZ2

