#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_ASTERON_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_ASTERON_
const uint8_t Animation_Asteron[] = {
	0,2,1,0,1,255,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_ASTERON

