#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_BOSSEHZ_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_BOSSEHZ_
const uint8_t Animation_BossEHZ[] = {
	0,4,0,7,15,0,255,7,1,2,255,0,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_BOSSEHZ

