#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_COCONUTS_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_COCONUTS_
const uint8_t Animation_Coconuts[] = {
	0,4,0,8,5,0,1,255,9,1,2,1,255,0,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_COCONUTS

