#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_SLICERPINCERS_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_SLICERPINCERS_
const uint8_t Animation_SlicerPincers[] = {
	0,2,3,5,6,7,8,255,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_SLICERPINCERS

