#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_WATERSPLASH_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_WATERSPLASH_
const uint8_t Animation_WaterSplash[] = {
	0,2,4,0,1,2,252,0,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_ANIMATION_WATERSPLASH

