#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_RES_RINGLAYOUT_ENDING_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_RES_RINGLAYOUT_ENDING_
const uint8_t RingLayout_Ending[] = {
	255,255,0,0,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_RES_RINGLAYOUT_ENDING

