#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_RES_RINGLAYOUT_FZ_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_RES_RINGLAYOUT_FZ_
const uint8_t RingLayout_FZ[] = {
	33,90,37,142,255,255,0,0,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_RES_RINGLAYOUT_FZ

