// Sonic 2's level data: which art, maps, layouts, collision, objects and rings each zone slot and act is made of, where the player starts, how far the level reaches and how the background scrolls.
// GENERATED by tools/import_s2sw_levels.pl from the Simon Wai prototype's SonLVL project (its zone ids are the slots, see ZoneIds.h; the prototype's "Green Hill" is Emerald Hill). Level.c (the loading and the
// level's state) reads them through Level.h. The slots of zones that are not in the prototype's data are zero.
#include "Level.h"

#include "Constants.h"
#include "Game.h"
#include "PLC.h"
#include "Palette.h"

#include <string.h>

// EHZ
#include "Resource/S2Art/EHZ.h"
#include "Resource/S2Map16/EHZ.h"
#include "Resource/S2Map128/EHZ.h"
#include "Resource/S2Collision/EHZ1.h"
#include "Resource/S2Collision/EHZ2.h"
// WZ
#include "Resource/S2Art/WZ.h"
#include "Resource/S2Map16/WZ.h"
#include "Resource/S2Map128/WZ.h"
#include "Resource/S2Collision/WZ1.h"
#include "Resource/S2Collision/WZ2.h"
// MTZ
#include "Resource/S2Art/MTZ.h"
#include "Resource/S2Map16/MTZ.h"
#include "Resource/S2Map128/MTZ.h"
#include "Resource/S2Collision/MTZ1.h"
#include "Resource/S2Collision/MTZ2.h"
// HTZ
#include "Resource/S2Art/HTZ.h"
#include "Resource/S2Map16/HTZ.h"
#include "Resource/S2Map128/HTZ.h"
#include "Resource/S2Collision/HTZ1.h"
#include "Resource/S2Collision/HTZ2.h"
// HPZ
#include "Resource/S2Art/HPZ.h"
#include "Resource/S2Map16/HPZ.h"
#include "Resource/S2Map128/HPZ.h"
#include "Resource/S2Collision/HPZ1.h"
#include "Resource/S2Collision/HPZ2.h"
// OOZ
#include "Resource/S2Art/OOZ.h"
#include "Resource/S2Map16/OOZ.h"
#include "Resource/S2Map128/OOZ.h"
#include "Resource/S2Collision/OOZ1.h"
#include "Resource/S2Collision/OOZ2.h"
// DHZ
#include "Resource/S2Art/DHZ.h"
#include "Resource/S2Map16/DHZ.h"
#include "Resource/S2Map128/DHZ.h"
#include "Resource/S2Collision/DHZ1.h"
#include "Resource/S2Collision/DHZ2.h"
// CNZ
#include "Resource/S2Art/CNZ.h"
#include "Resource/S2Map16/CNZ.h"
#include "Resource/S2Map128/CNZ.h"
#include "Resource/S2Collision/CNZ1.h"
#include "Resource/S2Collision/CNZ2.h"
// CPZ
#include "Resource/S2Art/CPZ.h"
#include "Resource/S2Map16/CPZ.h"
#include "Resource/S2Map128/CPZ.h"
#include "Resource/S2Collision/CPZ1.h"
#include "Resource/S2Collision/CPZ2.h"
// NGHZ
#include "Resource/S2Art/NGHZ.h"
#include "Resource/S2Map16/NGHZ.h"
#include "Resource/S2Map128/NGHZ.h"
#include "Resource/S2Collision/NGHZ1.h"
#include "Resource/S2Collision/NGHZ2.h"
#include "Resource/S2Layout/EHZ1.h"
#include "Resource/S2Objects/EHZ1.h"
#include "Resource/S2Rings/EHZ1.h"
#include "Resource/S2Layout/EHZ2.h"
#include "Resource/S2Objects/EHZ2.h"
#include "Resource/S2Rings/EHZ2.h"
#include "Resource/S2Layout/WZ1.h"
#include "Resource/S2Objects/WZ1.h"
#include "Resource/S2Rings/WZ1.h"
#include "Resource/S2Layout/WZ2.h"
#include "Resource/S2Objects/WZ2.h"
#include "Resource/S2Rings/WZ2.h"
#include "Resource/S2Layout/MTZ1.h"
#include "Resource/S2Objects/MTZ1.h"
#include "Resource/S2Rings/MTZ1.h"
#include "Resource/S2Layout/MTZ2.h"
#include "Resource/S2Objects/MTZ2.h"
#include "Resource/S2Rings/MTZ2.h"
#include "Resource/S2Layout/MTZ3.h"
#include "Resource/S2Objects/MTZ3.h"
#include "Resource/S2Rings/MTZ3.h"
#include "Resource/S2Layout/HTZ1.h"
#include "Resource/S2Objects/HTZ1.h"
#include "Resource/S2Rings/HTZ1.h"
#include "Resource/S2Layout/HTZ2.h"
#include "Resource/S2Objects/HTZ2.h"
#include "Resource/S2Rings/HTZ2.h"
#include "Resource/S2Layout/HPZ1.h"
#include "Resource/S2Objects/HPZ1.h"
#include "Resource/S2Rings/HPZ1.h"
#include "Resource/S2Layout/OOZ1.h"
#include "Resource/S2Objects/OOZ1.h"
#include "Resource/S2Rings/OOZ1.h"
#include "Resource/S2Layout/OOZ2.h"
#include "Resource/S2Objects/OOZ2.h"
#include "Resource/S2Rings/OOZ2.h"
#include "Resource/S2Layout/DHZ1.h"
#include "Resource/S2Objects/DHZ1.h"
#include "Resource/S2Rings/DHZ1.h"
#include "Resource/S2Layout/DHZ2.h"
#include "Resource/S2Objects/DHZ2.h"
#include "Resource/S2Rings/DHZ2.h"
#include "Resource/S2Layout/CNZ1.h"
#include "Resource/S2Objects/CNZ1.h"
#include "Resource/S2Rings/CNZ1.h"
#include "Resource/S2Layout/CNZ2.h"
#include "Resource/S2Objects/CNZ2.h"
#include "Resource/S2Rings/CNZ2.h"
#include "Resource/S2Layout/CPZ1.h"
#include "Resource/S2Objects/CPZ1.h"
#include "Resource/S2Rings/CPZ1.h"
#include "Resource/S2Layout/CPZ2.h"
#include "Resource/S2Objects/CPZ2.h"
#include "Resource/S2Rings/CPZ2.h"
#include "Resource/S2Layout/NGHZ1.h"
#include "Resource/S2Objects/NGHZ1.h"
#include "Resource/S2Rings/NGHZ1.h"
#include "Resource/S2Layout/NGHZ2.h"
#include "Resource/S2Objects/NGHZ2.h"
#include "Resource/S2Rings/NGHZ2.h"

// An act without objects
static const uint8_t obj_null[] = { 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00 };

// Level definitions: one combined (interleaved FG+BG, Kosinski) blob per act. An act the prototype has no layout for starts the zone's first.
const struct LevelLayout level_layouts[ZoneId_Num][4] = {
    [0x00] = {{ S2Layout_EHZ1 }, { S2Layout_EHZ2 }, { S2Layout_EHZ1 }, { S2Layout_EHZ1 } }, // EHZ
    [0x02] = {{ S2Layout_WZ1 }, { S2Layout_WZ2 }, { S2Layout_WZ1 }, { S2Layout_WZ1 } }, // WZ
    [0x04] = {{ S2Layout_MTZ1 }, { S2Layout_MTZ2 }, { S2Layout_MTZ1 }, { S2Layout_MTZ1 } }, // MTZ
    [0x05] = {{ S2Layout_MTZ3 }, { S2Layout_MTZ3 }, { S2Layout_MTZ3 }, { S2Layout_MTZ3 } }, // MTZ
    [0x07] = {{ S2Layout_HTZ1 }, { S2Layout_HTZ2 }, { S2Layout_HTZ1 }, { S2Layout_HTZ1 } }, // HTZ
    [0x08] = {{ S2Layout_HPZ1 }, { S2Layout_HPZ1 }, { S2Layout_HPZ1 }, { S2Layout_HPZ1 } }, // HPZ
    [0x0A] = {{ S2Layout_OOZ1 }, { S2Layout_OOZ2 }, { S2Layout_OOZ1 }, { S2Layout_OOZ1 } }, // OOZ
    [0x0B] = {{ S2Layout_DHZ1 }, { S2Layout_DHZ2 }, { S2Layout_DHZ1 }, { S2Layout_DHZ1 } }, // DHZ
    [0x0C] = {{ S2Layout_CNZ1 }, { S2Layout_CNZ2 }, { S2Layout_CNZ1 }, { S2Layout_CNZ1 } }, // CNZ
    [0x0D] = {{ S2Layout_CPZ1 }, { S2Layout_CPZ2 }, { S2Layout_CPZ1 }, { S2Layout_CPZ1 } }, // CPZ
    [0x0F] = {{ S2Layout_NGHZ1 }, { S2Layout_NGHZ2 }, { S2Layout_NGHZ1 }, { S2Layout_NGHZ1 } }, // NGHZ
};

// The level boundaries and camera shifts of each act. They depend on the size of the picture (the wider or taller it is, the further the camera can see past the edges), which is chosen at run time, so the table is built when it is read.
const int16_t *LevelSizes(int zone, int act) {
    const int16_t table[ZoneId_Num][4][6] = {
        [0x00] = { // EHZ
            { 0x0004, 0x0000, 0x29A0 + SCREEN_WIDEADD2, 0x0000, 0x0320 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2940 + SCREEN_WIDEADD2, 0x0000, 0x0420 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x29A0 + SCREEN_WIDEADD2, 0x0000, 0x0320 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2940 + SCREEN_WIDEADD2, 0x0000, 0x0420 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x02] = { // WZ
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x04] = { // MTZ
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x05] = { // MTZ
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x07] = { // HTZ
            { 0x0004, 0x0000, 0x2800 + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2880 + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2800 + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2880 + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x08] = { // HPZ
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x0A] = { // OOZ
            { 0x0004, 0x0000, 0x2F80 + SCREEN_WIDEADD2, 0x0000, 0x0680 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2580 + SCREEN_WIDEADD2, 0x0000, 0x0680 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2F80 + SCREEN_WIDEADD2, 0x0000, 0x0680 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2580 + SCREEN_WIDEADD2, 0x0000, 0x0680 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x0B] = { // DHZ
            { 0x0004, 0x0000, 0x2380 + SCREEN_WIDEADD2, 0x03C0, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2180 + SCREEN_WIDEADD2, 0x0060, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2380 + SCREEN_WIDEADD2, 0x03C0, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2180 + SCREEN_WIDEADD2, 0x0060, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x0C] = { // CNZ
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x3FFF + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x0D] = { // CPZ
            { 0x0004, 0x0000, 0x2780 + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2880 + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2780 + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x2880 + SCREEN_WIDEADD2, 0x0000, 0x0720 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
        [0x0F] = { // NGHZ
            { 0x0004, 0x0000, 0x28C0 + SCREEN_WIDEADD2, 0x0200, 0x03A0 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x26C0 + SCREEN_WIDEADD2, 0x0180, 0x05A0 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x28C0 + SCREEN_WIDEADD2, 0x0200, 0x03A0 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
            { 0x0004, 0x0000, 0x26C0 + SCREEN_WIDEADD2, 0x0180, 0x05A0 + SCREEN_TALLADD, 96 + SCREEN_TALLADD2 },
        },
    };
    static int16_t result[6];
    memcpy(result, table[zone][act], sizeof(result));
    return result;
}

// Player start positions
const int16_t StartLocArray[ZoneId_Num][4][2] = {
    [0x00] = { { 0x0060, 0x028F }, { 0x0040, 0x02AF }, { 0x0060, 0x028F }, { 0x0060, 0x028F } }, // EHZ
    [0x02] = { { 0x0060, 0x01AC }, { 0x0040, 0x01AC }, { 0x0060, 0x01AC }, { 0x0060, 0x01AC } }, // WZ
    [0x04] = { { 0x0060, 0x028C }, { 0x0040, 0x05EC }, { 0x0060, 0x028C }, { 0x0060, 0x028C } }, // MTZ
    [0x05] = { { 0x0060, 0x01EC }, { 0x0060, 0x01EC }, { 0x0060, 0x01EC }, { 0x0060, 0x01EC } }, // MTZ
    [0x07] = { { 0x0040, 0x03AF }, { 0x0060, 0x068F }, { 0x0040, 0x03AF }, { 0x0040, 0x03AF } }, // HTZ
    [0x08] = { { 0x0230, 0x01AC }, { 0x0230, 0x01AC }, { 0x0230, 0x01AC }, { 0x0230, 0x01AC } }, // HPZ
    [0x0A] = { { 0x0060, 0x06AC }, { 0x0050, 0x056C }, { 0x0060, 0x06AC }, { 0x0060, 0x06AC } }, // OOZ
    [0x0B] = { { 0x0060, 0x06AC }, { 0x0060, 0x05AC }, { 0x0060, 0x06AC }, { 0x0060, 0x06AC } }, // DHZ
    [0x0C] = { { 0x0060, 0x028F }, { 0x0040, 0x02AF }, { 0x0060, 0x028F }, { 0x0060, 0x028F } }, // CNZ
    [0x0D] = { { 0x0030, 0x01EC }, { 0x0030, 0x012C }, { 0x0030, 0x01EC }, { 0x0030, 0x01EC } }, // CPZ
    [0x0F] = { { 0x0050, 0x037C }, { 0x0050, 0x037C }, { 0x0050, 0x037C }, { 0x0050, 0x037C } }, // NGHZ
};

// Level scroll block sizes
const int16_t BGScrollBlockSizes[ZoneId_Num][4] = {
    [0x00] = { 0x800, 0x100, 0x100, 0 },
    [0x02] = { 0x800, 0x100, 0x100, 0 },
    [0x04] = { 0x800, 0x100, 0x100, 0 },
    [0x05] = { 0x800, 0x100, 0x100, 0 },
    [0x07] = { 0x800, 0x100, 0x100, 0 },
    [0x08] = { 0x800, 0x100, 0x100, 0 },
    [0x0A] = { 0x800, 0x100, 0x100, 0 },
    [0x0B] = { 0x800, 0x100, 0x100, 0 },
    [0x0C] = { 0x800, 0x100, 0x100, 0 },
    [0x0D] = { 0x800, 0x100, 0x100, 0 },
    [0x0F] = { 0x800, 0x100, 0x100, 0 },
};

// Level headers (sprite art list, tileset, second art list, blocks, palette, chunks); Hill Top's blocks and tileset have its own over Emerald Hill's
const LevelHeader level_header[ZoneId_Num] = {
    [0x00] = { PlcId_SLZ, S2Art_EHZ, 0, S2Map16_EHZ, PalId_EHZ, S2Map128_EHZ },
    [0x02] = { PlcId_SBZ, S2Art_WZ, 0, S2Map16_WZ, PalId_WZ, S2Map128_WZ },
    [0x04] = { PlcId_SBZ, S2Art_MTZ, 0, S2Map16_MTZ, PalId_MTZ, S2Map128_MTZ },
    [0x05] = { PlcId_SBZ, S2Art_MTZ, 0, S2Map16_MTZ, PalId_MTZ, S2Map128_MTZ },
    [0x07] = { PlcId_SBZ, S2Art_HTZ, 0, S2Map16_HTZ, PalId_HTZ, S2Map128_EHZ },
    [0x08] = { PlcId_SYZ, S2Art_HPZ, 0, S2Map16_HPZ, PalId_HPZ, S2Map128_HPZ },
    [0x0A] = { PlcId_SBZ, S2Art_OOZ, 0, S2Map16_OOZ, PalId_OOZ, S2Map128_OOZ },
    [0x0B] = { PlcId_SBZ, S2Art_DHZ, 0, S2Map16_DHZ, PalId_DHZ, S2Map128_DHZ },
    [0x0C] = { PlcId_SBZ, S2Art_CNZ, 0, S2Map16_CNZ, PalId_CNZ, S2Map128_CNZ },
    [0x0D] = { PlcId_MZ, S2Art_CPZ, PlcId_MZ2, S2Map16_CPZ, PalId_CPZ, S2Map128_CPZ },
    [0x0F] = { PlcId_SBZ, S2Art_NGHZ, 0, S2Map16_NGHZ, PalId_NGHZ, S2Map128_NGHZ },
};

// Level collision indices, one file per path
const uint8_t* level_coli[ZoneId_Num - 1][2] = {
    [0x00] = { S2Collision_EHZ1, S2Collision_EHZ2 },
    [0x02] = { S2Collision_WZ1, S2Collision_WZ2 },
    [0x04] = { S2Collision_MTZ1, S2Collision_MTZ2 },
    [0x05] = { S2Collision_MTZ1, S2Collision_MTZ2 },
    [0x07] = { S2Collision_HTZ1, S2Collision_HTZ2 },
    [0x08] = { S2Collision_HPZ1, S2Collision_HPZ2 },
    [0x0A] = { S2Collision_OOZ1, S2Collision_OOZ2 },
    [0x0B] = { S2Collision_DHZ1, S2Collision_DHZ2 },
    [0x0C] = { S2Collision_CNZ1, S2Collision_CNZ2 },
    [0x0D] = { S2Collision_CPZ1, S2Collision_CPZ2 },
    [0x0F] = { S2Collision_NGHZ1, S2Collision_NGHZ2 },
};

// Level object layouts (Sonic 2 format: ObjectsManager.h), and the ring layouts in the same places
const uint8_t* level_obj[ZoneId_Num][4] = {
    [0x00] = { S2Objects_EHZ1, S2Objects_EHZ2, S2Objects_EHZ1, S2Objects_EHZ1 }, // EHZ
    [0x02] = { obj_null, obj_null, obj_null, obj_null }, // WZ
    [0x04] = { obj_null, obj_null, obj_null, obj_null }, // MTZ
    [0x05] = { obj_null, obj_null, obj_null, obj_null }, // MTZ
    [0x07] = { S2Objects_HTZ1, S2Objects_HTZ2, S2Objects_HTZ1, S2Objects_HTZ1 }, // HTZ
    [0x08] = { S2Objects_HPZ1, S2Objects_HPZ1, S2Objects_HPZ1, S2Objects_HPZ1 }, // HPZ
    [0x0A] = { obj_null, obj_null, obj_null, obj_null }, // OOZ
    [0x0B] = { obj_null, obj_null, obj_null, obj_null }, // DHZ
    [0x0C] = { obj_null, obj_null, obj_null, obj_null }, // CNZ
    [0x0D] = { S2Objects_CPZ1, S2Objects_CPZ2, S2Objects_CPZ1, S2Objects_CPZ1 }, // CPZ
    [0x0F] = { obj_null, obj_null, obj_null, obj_null }, // NGHZ
};

const uint8_t* level_ring[ZoneId_Num][4] = {
    [0x00] = { S2Rings_EHZ1, S2Rings_EHZ2, S2Rings_EHZ1, S2Rings_EHZ1 }, // EHZ
    [0x02] = { S2Rings_WZ1, S2Rings_WZ2, S2Rings_WZ1, S2Rings_WZ1 }, // WZ
    [0x04] = { S2Rings_MTZ1, S2Rings_MTZ2, S2Rings_MTZ1, S2Rings_MTZ1 }, // MTZ
    [0x05] = { S2Rings_MTZ3, S2Rings_MTZ3, S2Rings_MTZ3, S2Rings_MTZ3 }, // MTZ
    [0x07] = { S2Rings_HTZ1, S2Rings_HTZ2, S2Rings_HTZ1, S2Rings_HTZ1 }, // HTZ
    [0x08] = { S2Rings_HPZ1, S2Rings_HPZ1, S2Rings_HPZ1, S2Rings_HPZ1 }, // HPZ
    [0x0A] = { S2Rings_OOZ1, S2Rings_OOZ2, S2Rings_OOZ1, S2Rings_OOZ1 }, // OOZ
    [0x0B] = { S2Rings_DHZ1, S2Rings_DHZ2, S2Rings_DHZ1, S2Rings_DHZ1 }, // DHZ
    [0x0C] = { S2Rings_CNZ1, S2Rings_CNZ2, S2Rings_CNZ1, S2Rings_CNZ1 }, // CNZ
    [0x0D] = { S2Rings_CPZ1, S2Rings_CPZ2, S2Rings_CPZ1, S2Rings_CPZ1 }, // CPZ
    [0x0F] = { S2Rings_NGHZ1, S2Rings_NGHZ2, S2Rings_NGHZ1, S2Rings_NGHZ1 }, // NGHZ
};

