#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_MAPPINGS_CPZWORM_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_MAPPINGS_CPZWORM_
const uint8_t Mappings_CPZWorm[] = {
	0,2,0,1,248,5,0,0,0,0,255,248,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_MAPPINGS_CPZWORM

