#ifndef _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_MAPPINGS_FLOATINGPLATFORM_
#define _HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_MAPPINGS_FLOATINGPLATFORM_
const uint8_t Mappings_FloatingPlatform[] = {
	0,2,0,1,248,13,0,0,0,0,255,240,
	0,0,0,0,0,0,0,0
};
#endif //_HOME_DECK_PROJECTS_SONIC1PC_SONIC_THE_HEDGEHOG_2_RES_MAPPINGS_FLOATINGPLATFORM

